### ISSUE TITLE
[Request] Auto sync randomizer list between IDEs

### ISSUE THREAD

**Issue by Dragon-0609** [Unthrottled/theme-randomizer#143]
I have some IDEs of Jetbrains. In all of them I use The Doki Theme, AMII and Theme Randomizer.
I worked just in Rider for a while, so my list of random themes changed.
I have just updated those plugins in my PyCharm. But after update I have to reselect my list of random themes again. So, it'd be great if I can sync randomizer settings between IDEs. 
You could add a button `Sync from another IDE`, and let the user to select directory of IDE, or after clicking, it'll check all installed IDEs with Theme Randomizer, then, check which has recently updated settings.
The main idea is syncing list among IDEs

**Comment by Unthrottled** [comment]
That's a good idea, had a couple of questions.

- Would you be able to utilize the platform settings sync feature ? https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html
- If not, are you just expecting the settings to sync on the same machine?

**Comment by Dragon-0609** [comment]
> are you just expecting the settings to sync on the same machine?

Yes, I mainly work in my PC. I hardly ever work in my laptop.

**Comment by Unthrottled** [comment]
Aight, I'll at a feature that when enabled will auto-sync changes between all IDEs on the same machine. Shouldn't be to hard, because right now the plugin shares which themes have been seen across all local IDEs, that way you are more likely to get a unique random theme in each IDE.

Might be a little bit, I'll probably work on this when I add 2022.2 build support.

**Comment by Unthrottled** [comment]
So here is how I am thinking it will work.

The first IDE that you enable `Locally Auto-Sync Settings` in the settings & save will set the initial list. 

Then when you go to another IDE &  enable `Locally Auto-Sync Settings`, then the settings from the other IDE will overwrite the current settings (eg keeps it it sync with the first one).

As long as there is a centralized setting, that will overwrite the IDE settings, when `Locally Auto-Sync Settings`. When you disable the action, it will go back to the IDE specific setting.

**Comment by Unthrottled** [comment]
Hey! So I've got something around. Please [download & manually install](https://github.com/Unthrottled/theme-randomizer/releases/tag/v0.6.0) this version. See if it works as you would expect.
