### ISSUE TITLE
Plugin doesn't follow OS Dark Mode setting in Timed mode

### ISSUE THREAD

**Issue by TheFreezingChicken** [Unthrottled/theme-randomizer#202]
I am on Windows and I usually set the OS theme settings on Dark Mode during the evening and Light Mode during the morning.
If I set the plugin mode to "Match OS" it correctly follows the OS setting and only shuffles through the corresponding themes, but if I set the plugin mode to "Timed" then it shuffles through ALL themes without any discrimination between Light and Dark, completely ignoring the system setting.
Right now I tested this behavior only on the latest stable version of Android Studio, so I don't know if it happens in other IDEs as well.

**Comment by Unthrottled** [comment]
That's how the `Timed` mode is currently designed. A `Match OS` option can be added to the `Timed` mode's theme selection.

**Comment by Unthrottled** [comment]
Hey! You'll eventually be able to manually install the plugin once you can download from the release https://github.com/Unthrottled/theme-randomizer/releases/tag/v0.8.0 (once this action https://github.com/Unthrottled/theme-randomizer/actions/runs/3614729832 finishes)

I tested it on Mac, but not Windows, let me know if you run into any issues. Thanks!

**Comment by TheFreezingChicken** [comment]
Daaaaaang that was fast, I could've waited easily but thanks.
And yes, works like a charm 👍🏻

**Comment by Unthrottled** [comment]
Nice!

TBH, This was a quick fix and I just wanted to procrastinate on what I was working on.

**Comment by TheFreezingChicken** [comment]
I could never relate to that last sentence at all 🙄🙄🙄 `*insert more sarcasm here*`
