### ISSUE TITLE
JetBrains doesn't want to approve the release

### ISSUE THREAD

**Issue by mallowigi** [Unthrottled/theme-randomizer#277]
Since the code uses internal APIs and until I figure out what and if there are alternatives, JetBrains didn't approve the release, therefore the version 1.0.0 is not available in the marketplace.

In the meantime I have published a jar file in the repository that you can install manually.

**Comment by Ravisdo** [comment]
omg, the version 1.0.0 works again 👏 ❤️ 
If you've installed the previous version manually from the release tab it can be updated through phpstorm.
![Bildschirmfoto 2024-07-31 um 09 23 09](https://github.com/user-attachments/assets/3ce79db0-ee32-43d6-a324-08dc96572aa9)
Big thanks for the updated plugin
